/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author cafiy
 */
public class Odev_calismasi1 extends javax.swing.JFrame {
        String secilenler = " ";
    /**
     * Creates new form Odev_calismasi1
     */
    public Odev_calismasi1() {
        initComponents();
    }
    private void guncelleEkran(){
        lbl_ekran.setText(secilenler.trim());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ekran = new javax.swing.JLabel();
        cb_yapayzeka = new javax.swing.JCheckBox();
        cb_bilişim = new javax.swing.JCheckBox();
        cb_bilgisayar = new javax.swing.JCheckBox();
        cb_yazilim = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_ekran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ekran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        cb_yapayzeka.setText("Yapay Zeka Mühendisliği");
        cb_yapayzeka.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_yapayzeka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_yapayzekaActionPerformed(evt);
            }
        });

        cb_bilişim.setText("Bilişim Sistemleri Mühendisliği");
        cb_bilişim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_bilişim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bilişimActionPerformed(evt);
            }
        });

        cb_bilgisayar.setText("Bilgisayar Mühendisliği");
        cb_bilgisayar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_bilgisayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bilgisayarActionPerformed(evt);
            }
        });

        cb_yazilim.setText("Yazılım Mühendisliği");
        cb_yazilim.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_yazilim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_yazilimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_ekran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_yazilim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_bilgisayar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_bilişim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_yapayzeka, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_ekran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_yazilim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_bilgisayar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_yapayzeka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_bilişim)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_yapayzekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_yapayzekaActionPerformed
        // TODO add your handling code here:
         if(cb_yapayzeka.isSelected()){
            if(!secilenler.contains(cb_yapayzeka.getText())){
               secilenler += cb_yapayzeka.getText() + " ";
            }
            } else{
                secilenler = secilenler.replace(cb_yapayzeka.getText() + " " , " ");
            }
            guncelleEkran();
        
        
    }//GEN-LAST:event_cb_yapayzekaActionPerformed

    private void cb_bilişimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bilişimActionPerformed
        // TODO add your handling code here:
         if(cb_bilişim.isSelected()){
            if(!secilenler.contains(cb_bilişim.getText())){
               secilenler += cb_bilişim.getText() + " ";
            }
            } else{
                secilenler = secilenler.replace(cb_bilişim.getText() + " " , " ");
            }
            guncelleEkran();
        
       
    }//GEN-LAST:event_cb_bilişimActionPerformed

    private void cb_bilgisayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bilgisayarActionPerformed
        // TODO add your handling code here:
        if(cb_bilgisayar.isSelected()){
            if(!secilenler.contains(cb_bilgisayar.getText())){
               secilenler += cb_bilgisayar.getText() + " ";
            }
            } else{
                secilenler = secilenler.replace(cb_bilgisayar.getText() + " " , " ");
            }
            guncelleEkran();
       
      
    }//GEN-LAST:event_cb_bilgisayarActionPerformed
       
    private void cb_yazilimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_yazilimActionPerformed
        // TODO add your handling code here:        
        if(cb_yazilim.isSelected()){
         if(!secilenler.contains(cb_yazilim.getText())){
             secilenler += cb_yazilim.getText() + " ";
         } 
        } else{
            secilenler = secilenler.replace(cb_yazilim.getText() + " " , " ");
        }
        guncelleEkran();
    }//GEN-LAST:event_cb_yazilimActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odev_calismasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odev_calismasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odev_calismasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odev_calismasi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odev_calismasi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_bilgisayar;
    private javax.swing.JCheckBox cb_bilişim;
    private javax.swing.JCheckBox cb_yapayzeka;
    private javax.swing.JCheckBox cb_yazilim;
    private javax.swing.JLabel lbl_ekran;
    // End of variables declaration//GEN-END:variables
}
