/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.util.Random;
/**
 *
 * @author cafiy
 */
public class Y_calisma05 extends javax.swing.JFrame {
    String [] secenekler = {"taş" , "kağıt" , "makas"};
    Random rastgele = new Random();
    /**
     * Creates new form Y_calisma05
     */
    public Y_calisma05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_tas = new javax.swing.JButton();
        byn_kagıt = new javax.swing.JButton();
        btn_makas = new javax.swing.JButton();
        lbl_oyuncu = new javax.swing.JLabel();
        lbl_bilgisayar = new javax.swing.JLabel();
        lbl_sonuc = new javax.swing.JLabel();
        lbl_oyuncu2 = new javax.swing.JLabel();
        lbl_oyuncu3 = new javax.swing.JLabel();
        lbl_bilgisiEtiketi1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Taş - Kağıt - Makas");

        btn_tas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_tas.setForeground(new java.awt.Color(102, 0, 51));
        btn_tas.setText("TAŞ");
        btn_tas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tasActionPerformed(evt);
            }
        });

        byn_kagıt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        byn_kagıt.setForeground(new java.awt.Color(102, 0, 51));
        byn_kagıt.setText("KAĞIT");
        byn_kagıt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byn_kagıtActionPerformed(evt);
            }
        });

        btn_makas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_makas.setForeground(new java.awt.Color(102, 0, 51));
        btn_makas.setText("MAKAS");
        btn_makas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_makasActionPerformed(evt);
            }
        });

        lbl_oyuncu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_oyuncu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_oyuncu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_bilgisayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_bilgisayar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bilgisayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_sonuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_sonuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sonuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_oyuncu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_oyuncu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_oyuncu2.setText("Siz Seçtiniz");
        lbl_oyuncu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_oyuncu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_oyuncu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_oyuncu3.setText("Bilgisayar Seçti");
        lbl_oyuncu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_bilgisiEtiketi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_bilgisiEtiketi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bilgisiEtiketi1.setText("Sonuç");
        lbl_bilgisiEtiketi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_oyuncu2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_oyuncu3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_bilgisiEtiketi1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_oyuncu, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(byn_kagıt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_makas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tas)
                    .addComponent(byn_kagıt)
                    .addComponent(btn_makas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_oyuncu2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_oyuncu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_oyuncu3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bilgisiEtiketi1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void oyunuOyna(String oyuncuSecimi){
        int bilgisayarIndeksi = rastgele.nextInt(secenekler.length);
        String bilgisayarSecimi = secenekler[bilgisayarIndeksi];
        
        lbl_oyuncu.setText(oyuncuSecimi);
        lbl_bilgisayar.setText(bilgisayarSecimi);
        
        String sonuc = sonucuBelirle(oyuncuSecimi , bilgisayarSecimi);
        lbl_sonuc.setText(sonuc);       
    }
    private String sonucuBelirle (String oyuncu , String bilgisayar){
        if(oyuncu.equals(bilgisayar)){
            return "Beraber!";
        } else if ((oyuncu.equals("taş") && bilgisayar.equals("makas")) || 
                (oyuncu.equals("kağıt") && bilgisayar.equals("taş")) || 
                (oyuncu.equals("makas") && bilgisayar.equals("kağıt"))){
                return "Siz kazandınız";
        } else {
            return "Bilgisayar kazandı";
        }
    }
    
    private void btn_tasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tasActionPerformed
        // TODO add your handling code here:
        oyunuOyna("taş");
        
    }//GEN-LAST:event_btn_tasActionPerformed

    private void byn_kagıtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byn_kagıtActionPerformed
        // TODO add your handling code here:
        oyunuOyna("kağıt");
    }//GEN-LAST:event_byn_kagıtActionPerformed

    private void btn_makasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_makasActionPerformed
        // TODO add your handling code here:
        oyunuOyna("makas");
    }//GEN-LAST:event_btn_makasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Y_calisma05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Y_calisma05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Y_calisma05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Y_calisma05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Y_calisma05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_makas;
    private javax.swing.JButton btn_tas;
    private javax.swing.JButton byn_kagıt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_bilgisayar;
    private javax.swing.JLabel lbl_bilgisiEtiketi1;
    private javax.swing.JLabel lbl_oyuncu;
    private javax.swing.JLabel lbl_oyuncu2;
    private javax.swing.JLabel lbl_oyuncu3;
    private javax.swing.JLabel lbl_sonuc;
    // End of variables declaration//GEN-END:variables
}
