/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author cafiy
 */
public class EightApp_1 extends javax.swing.JFrame {
    private ArrayList<Integer> kullaniciSayilari = new ArrayList<>();
    private JLabel[] sonucEtiketleri;
    private ArrayList<Integer> cekilisSonucu = new ArrayList<>();

    /**
     * Creates new form EightApp_1
     */
    public EightApp_1() {
        initComponents();
        sonucEtiketleri = new JLabel[]{lbl_sayi1 , lbl_sayi2 , lbl_sayi3, lbl_sayi4, lbl_sayi5, lbl_sayi6};
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        lbl_sayi6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_sayi5 = new javax.swing.JLabel();
        lbl_sayi4 = new javax.swing.JLabel();
        lbl_sayi3 = new javax.swing.JLabel();
        lbl_sayi2 = new javax.swing.JLabel();
        lbl_sayi1 = new javax.swing.JLabel();
        btn_Cekilis = new javax.swing.JButton();
        btn_Kullanici = new javax.swing.JButton();

        jTabbedPane3.addTab("tab1", jTabbedPane4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_sayi6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sayi6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sayısal Loto");

        lbl_sayi5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sayi5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_sayi4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sayi4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_sayi3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sayi3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_sayi2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sayi2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_sayi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sayi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_Cekilis.setText("Çekiliş Yap");
        btn_Cekilis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CekilisActionPerformed(evt);
            }
        });

        btn_Kullanici.setText("Kullanıcı Giriş");
        btn_Kullanici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KullaniciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_sayi1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sayi2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sayi3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sayi4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sayi5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_sayi6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Kullanici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Cekilis, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_sayi6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_sayi5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sayi2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sayi4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sayi3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sayi1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Kullanici)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cekilis)))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CekilisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CekilisActionPerformed
        // TODO add your handling code here:
       if(kullaniciSayilari.size() != 6){
           JOptionPane.showMessageDialog(this, "Önce 6 adet sayı girirniz.","Uyarı", JOptionPane.WARNING_MESSAGE);
           return;
       }
       cekilisSonucu.clear();
       Random random = new Random();
       HashSet<Integer> uretilenSayilar = new HashSet<>();
       
       while(uretilenSayilar.size() < 6){
           int rastgeleSayi = random.nextInt(50) + 1; //1-50 arası rastgele sayı 
           uretilenSayilar.add(rastgeleSayi);
           
       }
       cekilisSonucu.addAll(uretilenSayilar);
      // Collections.sort(cekilisSonucu); //Çekiliş sonucunu sırala
       //for( int dongu : cekilisSonucu){
         JOptionPane.showMessageDialog(this, "Çekiliş Sonucu: " + cekilisSonucu, "Çekiliş Sonucu" , JOptionPane.INFORMATION_MESSAGE);  
       //}
       
       
        // Kullanıcı tahminleriyle karşılaştır ve doğru sayıyı göster
       int dogruTahminSayisi = 0;
       for ( int kullaniciSaayisi : kullaniciSayilari){
           boolean bulundu = false;
           for( int cekilisSayisi : cekilisSonucu){
               if(kullaniciSaayisi == cekilisSayisi){
                   dogruTahminSayisi++;
                   bulundu = true;
                   break;
               }
           }
       }
       //for( int tahmin : kullaniciSayilari){
       //    if(cekilisSonucu.contains(tahmin)){
       //        dogruTahminSayisi++;
       //    }
      // }
       JOptionPane.showMessageDialog(this , "Doğru Tahmin Sayısı: " + dogruTahminSayisi , "Sonuç" , JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btn_CekilisActionPerformed

    private void btn_KullaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KullaniciActionPerformed
        // TODO add your handling code here:
        kullaniciSayilari.clear();
        HashSet<Integer> girilenSayilar = new HashSet<>(); //TEKRAR EDEN SAYILARI ÖNELEMEK İÇİN
        for(int i = 0; i< sonucEtiketleri.length; i++){
            String giris = JOptionPane.showInputDialog(this , (i+1) + ". sayıyı girirniz: " , JOptionPane.QUESTION_MESSAGE);
            if(giris != null && !giris.trim().isEmpty()){
                try {
                    int sayi = Integer.parseInt(giris.trim());
                    if( sayi >= 1 && sayi <= 50){
                       if(girilenSayilar.add(sayi)){  // Sayı daha önce girilmediyse kümeye ekle
                           kullaniciSayilari.add(sayi);
                           sonucEtiketleri[i].setText(String.valueOf(sayi)); // Label'da göster
                          
                       } else{
                           JOptionPane.showMessageDialog(this , " Bu sayoya daha önce girdiniz. " ," HATA" , JOptionPane.ERROR_MESSAGE);
                           //kullaniciSayilari.clear();
                           for(JLabel etiket : sonucEtiketleri ){
                               //etiket.setText("");  //HATA DURUMUNDA ETİKETLERİ TEMİZLE
                           }
                           return; //METOTTAN ÇIK
                       }
                    } else {
                        JOptionPane.showMessageDialog (this , "Sayı 1- 50 arasında olmalı." , "HATA", JOptionPane.ERROR_MESSAGE);
                        //kullaniciSayilari.clear();
                        for(JLabel etiket : sonucEtiketleri){
                          //  etiket.setText(""); //HATA DURUMUNDAN ETİKETLERİ TEMİZLE
                        }
                        return; //METTOTTAN ÇIK
                    }
                } catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Gçerli bir sayı giriniz." , "HATA" , JOptionPane.ERROR_MESSAGE);
                   // kullaniciSayilari.clear();
                    for(JLabel etiket : sonucEtiketleri){
                      //  etiket.setText(""); //Hata durumunda etiketleri temizle
                        
                    }
                    return; //Metootan çık
                }
            } else{
                JOptionPane.showMessageDialog(this," Lütfen bir sayı giriniz." , "Hata" , JOptionPane.ERROR_MESSAGE);
               // kullaniciSayilari.clear();
                for(JLabel etiket : sonucEtiketleri){
                  //  etiket.setText(""); //HATA DURUMUNDA ETİKETLERİ TEMİZLE
                }
                return; //Metottan çık
            }
        }
        if(kullaniciSayilari.size()==6){
            JOptionPane.showMessageDialog(this, "Girilen sayılar: " + kullaniciSayilari , "Başarılı" , JOptionPane.INFORMATION_MESSAGE);
            
        }
       
        
        
    }//GEN-LAST:event_btn_KullaniciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EightApp_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EightApp_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EightApp_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EightApp_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EightApp_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cekilis;
    private javax.swing.JButton btn_Kullanici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel lbl_sayi1;
    private javax.swing.JLabel lbl_sayi2;
    private javax.swing.JLabel lbl_sayi3;
    private javax.swing.JLabel lbl_sayi4;
    private javax.swing.JLabel lbl_sayi5;
    private javax.swing.JLabel lbl_sayi6;
    // End of variables declaration//GEN-END:variables
}
